services:
  webdav:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webdav.rule=Host(`${FQDN_WEBDAV:-webdav.test}`)"
      - "traefik.http.routers.webdav.entrypoints=websecure"
      - "traefik.http.routers.webdav.tls=true"
      - "traefik.http.services.webdav.loadbalancer.server.port=80"

networks:
  default:
    name: ${NETWORK_NAME:-traefik-network}
    external: true
