services:

  webdav:
    build:
      context: .
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    init: true
    ports:
      - "${PORT}:80"
    volumes:
      - ${MEDIA_PATH}:/media/data:ro
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      TZ: ${TIMEZONE}
    restart: unless-stopped
